/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FeedbackFormContract
  extends Truffle.Contract<FeedbackFormInstance> {
  "new"(
    _title: string,
    _description: string,
    meta?: Truffle.TransactionDetails
  ): Promise<FeedbackFormInstance>;
}

type AllEvents = never;

export interface FeedbackFormInstance extends Truffle.ContractInstance {
  description(txDetails?: Truffle.TransactionDetails): Promise<string>;

  feedbackProviders(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  questions(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  title(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getHasProvidedFeedback(
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  setQuestions: {
    (_questions: string[], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _questions: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _questions: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _questions: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getQuestionById(
    _id: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: string; 1: BN[] }>;

  getAllQuestions(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ value: string; feedback: BN[] }[]>;

  submitFeedback: {
    (
      _feedback: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _feedback: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _feedback: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _feedback: (number | BN | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    description(txDetails?: Truffle.TransactionDetails): Promise<string>;

    feedbackProviders(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    questions(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    title(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getHasProvidedFeedback(
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    setQuestions: {
      (_questions: string[], txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _questions: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _questions: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _questions: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getQuestionById(
      _id: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: string; 1: BN[] }>;

    getAllQuestions(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ value: string; feedback: BN[] }[]>;

    submitFeedback: {
      (
        _feedback: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _feedback: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _feedback: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _feedback: (number | BN | string)[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
