/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ConvertLibContract } from "./ConvertLib";
import { FeedbackFormContract } from "./FeedbackForm";
import { FeedbackFormFactoryContract } from "./FeedbackFormFactory";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ConvertLib"): ConvertLibContract;
      require(name: "FeedbackForm"): FeedbackFormContract;
      require(name: "FeedbackFormFactory"): FeedbackFormFactoryContract;
    }
  }
}

export { ConvertLibContract, ConvertLibInstance } from "./ConvertLib";
export { FeedbackFormContract, FeedbackFormInstance } from "./FeedbackForm";
export {
  FeedbackFormFactoryContract,
  FeedbackFormFactoryInstance,
} from "./FeedbackFormFactory";
